on:
    push:
      branches:
        - main
    pull_request:
        branches:
          - main
    
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2 

            - name: Copy files to good workspace
            - run: cp ./home/runner/_work/breizsport /ect/breizsport

            - name: Change directory
            - run: cd /ect/breizsport

            - name: Install dependencies & starting webserver
            - run: |
                npm install
                npm run start