on:
    push:
      branches:
        - main
    pull_request:
        branches:
          - main
    
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2 

            - name: "Copy files to good workspace"
              run: sudo cp -r /home/pi/actions-runner/_work/breizhsport /opt/breizhsport
            
            - name: "Change directory"
              run: cd /opt/breizhsport/breizhsport/backend

            - name: "Install dependencies & starting webserver"
              run: |
                npm install
                npm run start