on:
    push:
      branches:
        - main
    pull_request:
        branches:
          - main
    
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2 

            - run: cp ./home/runner/_work/breizsport /etc/breizsport